# /etc/bash/bashrc

[ -e /etc/profile ] && source /etc/profile

if [ -v "$(command -v shopt)" ]; then
    shopt -s checkwinsize
    shopt -s no_empty_cmd_completion
    shopt -s histappend
fi

unset sh
