" /etc/vimrc

scriptencoding utf-8                              " Set script as UTF-8
set nocompatible                                  " be iMproved, required

set encoding=utf-8                                " Set encoding to UTF-8
set termencoding=utf-8                            " UTF8 as default encoding

set nobackup                                      "
set nomodeline                                    " Disable modeline globally
set noswapfile                                    "
set scrolloff=100                                 "

set bs=2                                          " Backspace over everything
set clipboard=unnamedplus                         " Share X11 clipboard
set listchars=tab:\|.,trail:.,extends:#,nbsp:.    "
set pastetoggle=<F2>                              "
set t_BE=                                         " Disable bracketed paste

set ai                                            " Auto-indent in insert mode
set list                                          " Show whitespace
set number                                        " Show line numbers
set ruler
set wrap linebreak nolist                         "
autocmd BufWritePre * %s/\s\+$//e                 " Delete trailing whitespace on save

set mouse=a                                       " Enable mouse support

map Q gq                                          " Use Q for formatting, not Ex mode
nmap <silent> <leader>/ :nohlsearch<CR>           " Use <leader>/ to clear search highlight

nnoremap <C-h> <C-w>h                             "
nnoremap <C-j> <C-w>j                             "
nnoremap <C-k> <C-w>k                             "
nnoremap <C-l> <C-w>l                             "

inoremap <leader>z <C-O>za                        " Fold mappings
nnoremap <leader>z za                             " ...
onoremap <leader>z <C-C>za                        " ...
vnoremap <leader>z zf                             " ...
