# ~/.zshrc

### Setup

ZSH="/home/$(whoami)/.oh-my-zsh"
if [ ! -d "$ZSH" ]; then
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
fi

plugins=(git go man)
ZSH_THEME="risto"
COMPLETION_WAITING_DOTS="true"
source "$ZSH"/oh-my-zsh.sh


### Settings

[ -e /etc/profile ] && source /etc/profile

if [ -n "$TMUX" ]; then
    unset zle_bracketed_paste
fi
